using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;

using Rhino.Geometry;

using Alpaca4d.BeamIntegration;
using Alpaca4d.Constraints;
using Alpaca4d.Element;
using Alpaca4d.Generic;
using Alpaca4d.Loads;
using Alpaca4d.Material;
using Alpaca4d.Section;
using Alpaca4d.TimeSeries;

namespace Alpaca4d
{
    /// <summary>
    /// Reads an OpenSees .tcl input deck back into an <see cref="Alpaca4d.Model"/>, so a deck that
    /// Alpaca4d wrote (or a hand written one that stays inside the subset Alpaca4d understands) can be
    /// put back on the canvas, viewed with Model View and re-analysed.
    ///
    /// The model that comes out is a real assembled model, not a drawing: elements carry their sections
    /// and materials, supports and loads are attached to node positions, and <see cref="Model.Tcl"/> is
    /// regenerated by <see cref="Model.Assemble"/> rather than copied from the input.
    ///
    /// Section, material, time series and load pattern tags are re-issued rather than kept, so they need
    /// not match the input file; nothing refers to them across the round trip. Node and element tags are
    /// derived by <see cref="Model.Assemble"/> from the element order, which is the file order, so a deck
    /// Alpaca4d wrote does come back numbered as it went out.
    ///
    /// Anything outside the supported subset is skipped and reported in <see cref="Warnings"/> instead of
    /// throwing, so a deck with, say, a truss in it still yields the part of the model that is readable.
    /// </summary>
    public class TclReader
    {
        // Only the commands that describe the model are read. Everything the analysis needs
        // (recorder, system, algorithm, analyze, ...) is added by Run Analysis, not stored here.
        private static readonly HashSet<string> IgnoredCommands = new HashSet<string>(StringComparer.OrdinalIgnoreCase)
        {
            "wipe", "wipeAnalysis", "recorder", "constraints", "numberer", "system", "test",
            "algorithm", "integrator", "analysis", "analyze", "eigen", "rayleigh", "modalProperties",
            "record", "loadConst", "setTime", "remove", "puts", "reset", "print", "database",
            "logFile", "defaultUnits", "set", "source", "if", "for", "foreach", "while", "proc",
        };

        private readonly double _tolerance;
        private readonly List<string> _warnings = new List<string>();

        // Everything the first pass gathers, keyed by the tag used in the file.
        private readonly Dictionary<int, Point3d> _nodes = new Dictionary<int, Point3d>();
        private readonly Dictionary<int, int> _nodeNdf = new Dictionary<int, int>();
        private readonly Dictionary<int, IMultiDimensionMaterial> _ndMaterials = new Dictionary<int, IMultiDimensionMaterial>();
        private readonly Dictionary<int, ElasticSection> _uniaxialSections = new Dictionary<int, ElasticSection>();
        private readonly Dictionary<int, PlateFiberSection> _plateSections = new Dictionary<int, PlateFiberSection>();
        private readonly Dictionary<int, (GeomTransfType Type, Vector3d LocalZ)> _transforms = new Dictionary<int, (GeomTransfType, Vector3d)>();
        private readonly Dictionary<int, ITimeSeries> _timeSeries = new Dictionary<int, ITimeSeries>();

        // What the second pass builds.
        private readonly List<IElement> _elements = new List<IElement>();
        private readonly Dictionary<int, IBeam> _beamsByTag = new Dictionary<int, IBeam>();
        private readonly List<Support> _supports = new List<Support>();
        private readonly List<LoadPattern> _patterns = new List<LoadPattern>();
        private readonly List<IConstraint> _constraints = new List<IConstraint>();
        private readonly List<MassLoad> _masses = new List<MassLoad>();

        private TclReader(double tolerance)
        {
            _tolerance = tolerance;
        }

        /// <summary>Everything that could not be read, one message per cause.</summary>
        public IReadOnlyList<string> Warnings => _warnings;

        /// <summary>The assembled model. Never null; it is empty when the deck held nothing readable.</summary>
        public Model Model { get; private set; }

        public static TclReader ReadFile(string filePath, double tolerance = 0.01)
        {
            if (string.IsNullOrWhiteSpace(filePath))
                throw new ArgumentException("No file path was given.", nameof(filePath));
            if (!System.IO.File.Exists(filePath))
                throw new System.IO.FileNotFoundException($"There is no file at \"{filePath}\".", filePath);

            return ReadText(System.IO.File.ReadAllLines(filePath), tolerance);
        }

        public static TclReader ReadText(IEnumerable<string> text, double tolerance = 0.01)
        {
            if (text == null)
                throw new ArgumentNullException(nameof(text));

            var reader = new TclReader(tolerance <= 0.0 ? 0.01 : tolerance);
            reader.Read(Tokenize(text));
            return reader;
        }

        #region lexing

        /// <summary>
        /// Splits the input into one token array per Tcl command. A single item of the incoming list can
        /// hold several commands separated by newlines - that is exactly what the Serialize component
        /// hands out, since every WriteTcl() ends in "\n" and some emit more than one line - so the
        /// newlines have to be honoured as command separators rather than swallowed as whitespace.
        /// </summary>
        private static List<string[]> Tokenize(IEnumerable<string> text)
        {
            var separators = new[] { "\r\n", "\n", "\r" };
            var commands = new List<string[]>();

            foreach (var chunk in text)
            {
                if (chunk == null)
                    continue;

                foreach (var line in chunk.Split(separators, StringSplitOptions.None))
                {
                    // Braces are their own tokens: a load pattern body opens with "... -fact 1 {" and
                    // closes with a bare "}", and a Path series writes "-time {1 2 3}" with no spaces.
                    var spaced = line.Replace("{", " { ").Replace("}", " } ");
                    var tokens = spaced.Split(new[] { ' ', '\t' }, StringSplitOptions.RemoveEmptyEntries);

                    if (tokens.Length == 0)
                        continue;
                    if (tokens[0].StartsWith("#"))
                        continue;

                    commands.Add(tokens);
                }
            }

            return commands;
        }

        private static bool TryNumber(string token, out double value)
        {
            const NumberStyles style = NumberStyles.Float;

            if (double.TryParse(token, style, CultureInfo.InvariantCulture, out value))
                return true;

            // A deck written by an older Alpaca4d on a machine with a comma decimal separator is not
            // valid Tcl, but it is what the user has; read it rather than fail on it.
            return double.TryParse(token, style, CultureInfo.CurrentCulture, out value);
        }

        private static bool TryTag(string token, out int tag)
        {
            if (int.TryParse(token, NumberStyles.Integer, CultureInfo.InvariantCulture, out tag))
                return true;

            // "1.0" is a legal Tcl spelling of the tag 1.
            if (TryNumber(token, out double asDouble) && Math.Abs(asDouble % 1.0) < 1e-9)
            {
                tag = (int)Math.Round(asDouble);
                return true;
            }

            tag = 0;
            return false;
        }

        private static double Number(string[] tokens, int index)
        {
            if (index >= tokens.Length || !TryNumber(tokens[index], out double value))
                throw new FormatException($"Expected a number at position {index + 1} of \"{string.Join(" ", tokens)}\".");
            return value;
        }

        private static int Tag(string[] tokens, int index)
        {
            if (index >= tokens.Length || !TryTag(tokens[index], out int tag))
                throw new FormatException($"Expected a tag at position {index + 1} of \"{string.Join(" ", tokens)}\".");
            return tag;
        }

        /// <summary>Reads an optional trailing value such as "-mass 12.5", returning null when absent or blank.</summary>
        private static double? OptionalFlagValue(string[] tokens, string flag)
        {
            for (int i = 0; i < tokens.Length - 1; i++)
            {
                if (string.Equals(tokens[i], flag, StringComparison.OrdinalIgnoreCase))
                    return TryNumber(tokens[i + 1], out double value) ? value : (double?)null;
            }
            return null;
        }

        private static bool HasFlag(string[] tokens, string flag)
        {
            return tokens.Any(t => string.Equals(t, flag, StringComparison.OrdinalIgnoreCase));
        }

        #endregion

        #region reading

        private void Read(List<string[]> commands)
        {
            ReadDefinitions(commands);
            ReadTopology(commands);

            Model = new Model(_elements, _supports, _patterns, _constraints, new List<IRecorder>())
            {
                Tollerance = _tolerance,
                Mass = _masses,
            };

            if (_elements.Count == 0)
            {
                Warn("The file holds no element Alpaca4d can build, so the model is empty.");
                return;
            }

            try
            {
                Model.Assemble();
            }
            catch (Exception ex)
            {
                // Assembly usually fails because of what was skipped earlier - a support left hanging
                // on a node whose element could not be read, say - so the failure is only legible next
                // to the warnings that led to it.
                throw new InvalidOperationException(
                    _warnings.Count == 0
                        ? ex.Message
                        : ex.Message + Environment.NewLine + "While reading the file: " + string.Join(" ", _warnings),
                    ex);
            }
        }

        /// <summary>
        /// First pass: nodes, materials, sections, transformations and time series. These are read up
        /// front because a hand written deck is free to define them after the elements that use them.
        /// </summary>
        private void ReadDefinitions(List<string[]> commands)
        {
            int ndf = 6;

            foreach (var tokens in commands)
            {
                try
                {
                    switch (tokens[0].ToLowerInvariant())
                    {
                        case "model":
                            var declared = OptionalFlagValue(tokens, "-ndf");
                            if (declared.HasValue)
                                ndf = (int)declared.Value;
                            break;

                        case "node":
                            ReadNode(tokens, ndf);
                            break;

                        case "uniaxialmaterial":
                            // Alpaca4d rebuilds a beam material out of its section line, which carries E,
                            // G and (via -mass) rho, so the standalone material line adds nothing. It is
                            // still worth a warning when it is something other than plain Elastic.
                            if (!string.Equals(tokens[1], "Elastic", StringComparison.OrdinalIgnoreCase))
                                Warn($"uniaxialMaterial {tokens[1]} is not supported and was skipped.");
                            break;

                        case "ndmaterial":
                            ReadNdMaterial(tokens);
                            break;

                        case "section":
                            ReadSection(tokens);
                            break;

                        case "geomtransf":
                            ReadGeomTransf(tokens);
                            break;

                        case "timeseries":
                            ReadTimeSeries(tokens);
                            break;
                    }
                }
                catch (Exception ex)
                {
                    Warn($"Could not read \"{string.Join(" ", tokens)}\": {ex.Message}");
                }
            }
        }

        /// <summary>Second pass: everything that points at a node, an element, a section or a series.</summary>
        private void ReadTopology(List<string[]> commands)
        {
            LoadPattern openPattern = null;
            List<ILoad> openPatternLoads = null;

            foreach (var tokens in commands)
            {
                try
                {
                    var command = tokens[0].ToLowerInvariant();

                    if (command == "}")
                    {
                        if (openPattern != null)
                        {
                            openPattern.Load = openPatternLoads;
                            _patterns.Add(openPattern);
                            openPattern = null;
                            openPatternLoads = null;
                        }
                        continue;
                    }

                    // Inside a pattern body only the load commands are of interest.
                    if (openPattern != null)
                    {
                        if (command == "load")
                            openPatternLoads.Add(ReadNodalLoad(tokens, openPattern.TimeSeries));
                        else if (command == "eleload")
                            openPatternLoads.Add(ReadElementLoad(tokens, openPattern.TimeSeries));
                        else if (command != "{")
                            Warn($"\"{tokens[0]}\" inside a load pattern is not supported and was skipped.");
                        continue;
                    }

                    switch (command)
                    {
                        case "fix":
                            ReadFix(tokens);
                            break;

                        case "element":
                            ReadElement(tokens);
                            break;

                        case "mass":
                            ReadMass(tokens);
                            break;

                        case "equaldof":
                            ReadEqualDof(tokens);
                            break;

                        case "rigiddiaphragm":
                            ReadRigidDiaphragm(tokens);
                            break;

                        case "rigidlink":
                            ReadRigidLink(tokens);
                            break;

                        case "pattern":
                            (openPattern, openPatternLoads) = ReadPattern(tokens);
                            break;

                        // Handled by the first pass or deliberately not part of the model.
                        case "model":
                        case "node":
                        case "uniaxialmaterial":
                        case "ndmaterial":
                        case "section":
                        case "geomtransf":
                        case "timeseries":
                        case "{":
                            break;

                        default:
                            if (!IgnoredCommands.Contains(tokens[0]))
                                Warn($"\"{tokens[0]}\" is not supported and was skipped.");
                            break;
                    }
                }
                catch (Exception ex)
                {
                    Warn($"Could not read \"{string.Join(" ", tokens)}\": {ex.Message}");
                }
            }

            // A pattern whose closing brace never arrived still holds real loads.
            if (openPattern != null)
            {
                openPattern.Load = openPatternLoads;
                _patterns.Add(openPattern);
                Warn("A load pattern was left unclosed; its loads were kept.");
            }
        }

        #endregion

        #region definitions

        private void ReadNode(string[] tokens, int ndf)
        {
            int tag = Tag(tokens, 1);
            var position = new Point3d(Number(tokens, 2), Number(tokens, 3), Number(tokens, 4));

            if (_nodes.ContainsKey(tag))
            {
                Warn($"Node {tag} is defined more than once; the first definition was kept.");
                return;
            }

            _nodes.Add(tag, position);
            _nodeNdf.Add(tag, ndf);

            // "node 1 x y z -mass m m m ..." is a lumped mass in disguise; Alpaca4d keeps those as
            // MassLoad objects, and writes zeros on the node line itself.
            int massAt = Array.FindIndex(tokens, t => string.Equals(t, "-mass", StringComparison.OrdinalIgnoreCase));
            if (massAt < 0)
                return;

            var values = ReadTrailingNumbers(tokens, massAt + 1);
            if (values.Count >= 3 && values.Take(Math.Min(6, values.Count)).Any(v => Math.Abs(v) > 0.0))
                _masses.Add(new MassLoad(position,
                    MassLoad.FromModelUnits(Vector(values, 0)),
                    values.Count >= 6 ? MassLoad.FromModelUnits(Vector(values, 3)) : Vector3d.Zero));
        }

        private void ReadNdMaterial(string[] tokens)
        {
            int tag = Tag(tokens, 2);
            var type = tokens[1];

            if (string.Equals(type, "ElasticIsotropic", StringComparison.OrdinalIgnoreCase))
            {
                double e = Number(tokens, 3);
                double nu = Number(tokens, 4);
                double? rho = tokens.Length > 5 && TryNumber(tokens[5], out double r)
                    ? Alpaca4d.ModelMass.ToKg(r) : (double?)null;
                // G is not part of the command; for an isotropic material it is implied by E and nu.
                _ndMaterials[tag] = new ElasticIsotropicMaterial($"nDMaterial_{tag}", e, e / (2.0 * (1.0 + nu)), nu, rho);
            }
            else if (string.Equals(type, "ElasticOrthotropic", StringComparison.OrdinalIgnoreCase))
            {
                double? rho = tokens.Length > 12 && TryNumber(tokens[12], out double r)
                    ? Alpaca4d.ModelMass.ToKg(r) : (double?)null;
                _ndMaterials[tag] = new ElasticOrthotropicMaterial($"nDMaterial_{tag}",
                    Number(tokens, 3), Number(tokens, 4), Number(tokens, 5),
                    Number(tokens, 9), Number(tokens, 10), Number(tokens, 11),
                    Number(tokens, 6), Number(tokens, 7), Number(tokens, 8),
                    rho);
            }
            else
            {
                Warn($"nDMaterial {type} is not supported and was skipped.");
            }
        }

        private void ReadSection(string[] tokens)
        {
            int tag = Tag(tokens, 2);
            var type = tokens[1];

            // OpenSees keeps every section in one tag space, Elastic and PlateFiber alike, so a repeated
            // tag means one of the two definitions loses and the elements pointing at it get the other.
            // Say so rather than let the swap happen quietly.
            if (_uniaxialSections.ContainsKey(tag) || _plateSections.ContainsKey(tag))
            {
                Warn($"Section {tag} is defined more than once; the first definition was kept.");
                return;
            }

            if (string.Equals(type, "Elastic", StringComparison.OrdinalIgnoreCase))
            {
                // section Elastic $tag $E $A $Iz $Iy $G $J <$alphaY $alphaZ>
                double e = Number(tokens, 3);
                double area = Number(tokens, 4);
                double izz = Number(tokens, 5);
                double iyy = Number(tokens, 6);
                double g = Number(tokens, 7);
                double j = Number(tokens, 8);
                double alphaY = tokens.Length > 9 ? Number(tokens, 9) : 0.0;
                double alphaZ = tokens.Length > 10 ? Number(tokens, 10) : 0.0;

                // Poisson's ratio is implied by E and G. Density is not in the deck at all; it is
                // recovered later from the -mass the element carries.
                double nu = g > 0.0 ? (e / (2.0 * g)) - 1.0 : 0.0;
                var material = new UniaxialMaterialElastic($"Material_{tag}", e, e, 0.0, g, nu);

                _uniaxialSections[tag] = new ElasticSection($"Section_{tag}", area, izz, iyy, j, alphaY, alphaZ, material);
            }
            else if (string.Equals(type, "PlateFiber", StringComparison.OrdinalIgnoreCase))
            {
                int materialTag = Tag(tokens, 3);
                if (!_ndMaterials.TryGetValue(materialTag, out var material))
                {
                    Warn($"section PlateFiber {tag} refers to nDMaterial {materialTag}, which is not in the file.");
                    return;
                }
                _plateSections[tag] = new PlateFiberSection($"Section_{tag}", Number(tokens, 4), material);
            }
            else
            {
                Warn($"section {type} is not supported and was skipped.");
            }
        }

        private void ReadGeomTransf(string[] tokens)
        {
            int tag = Tag(tokens, 2);

            if (!Enum.TryParse(tokens[1], true, out GeomTransfType type))
            {
                Warn($"geomTransf {tokens[1]} is not supported; Linear was used instead.");
                type = GeomTransfType.Linear;
            }

            var localZ = tokens.Length > 5
                ? new Vector3d(Number(tokens, 3), Number(tokens, 4), Number(tokens, 5))
                : Vector3d.ZAxis;

            _transforms[tag] = (type, localZ);
        }

        private void ReadTimeSeries(string[] tokens)
        {
            int tag = Tag(tokens, 2);
            var type = tokens[1];
            double factor = OptionalFlagValue(tokens, "-factor") ?? 1.0;

            ITimeSeries series;
            if (string.Equals(type, "Constant", StringComparison.OrdinalIgnoreCase))
            {
                series = new Constant(factor);
            }
            else if (string.Equals(type, "Linear", StringComparison.OrdinalIgnoreCase))
            {
                series = new Linear(factor);
            }
            else if (string.Equals(type, "Trig", StringComparison.OrdinalIgnoreCase) ||
                     string.Equals(type, "Trigonometric", StringComparison.OrdinalIgnoreCase))
            {
                series = new Trigonometric(Number(tokens, 3), Number(tokens, 4), Number(tokens, 5),
                                           OptionalFlagValue(tokens, "-shift") ?? 0.0, factor);
            }
            else if (string.Equals(type, "Triangle", StringComparison.OrdinalIgnoreCase))
            {
                series = new Triangle(Number(tokens, 3), Number(tokens, 4), Number(tokens, 5),
                                      OptionalFlagValue(tokens, "-shift") ?? 0.0, factor);
            }
            else if (string.Equals(type, "Path", StringComparison.OrdinalIgnoreCase))
            {
                var times = ReadBracedNumbers(tokens, "-time");
                var values = ReadBracedNumbers(tokens, "-values");
                if (times.Count == 0 || values.Count == 0)
                {
                    Warn($"timeSeries Path {tag} has no -time/-values list Alpaca4d can read and was skipped.");
                    return;
                }
                series = new PathTimeSeries(times, values, factor);
            }
            else
            {
                Warn($"timeSeries {type} is not supported and was skipped.");
                return;
            }

            series.Id = tag;
            _timeSeries[tag] = series;
        }

        /// <summary>Reads the numbers of a "-flag { a b c }" list.</summary>
        private static List<double> ReadBracedNumbers(string[] tokens, string flag)
        {
            var values = new List<double>();

            int at = Array.FindIndex(tokens, t => string.Equals(t, flag, StringComparison.OrdinalIgnoreCase));
            if (at < 0 || at + 1 >= tokens.Length || tokens[at + 1] != "{")
                return values;

            for (int i = at + 2; i < tokens.Length && tokens[i] != "}"; i++)
            {
                if (TryNumber(tokens[i], out double value))
                    values.Add(value);
            }

            return values;
        }

        #endregion

        #region topology

        private void ReadFix(string[] tokens)
        {
            int tag = Tag(tokens, 1);
            if (!_nodes.TryGetValue(tag, out var position))
            {
                Warn($"fix refers to node {tag}, which is not in the file.");
                return;
            }

            var flags = new List<bool>();
            for (int i = 2; i < tokens.Length; i++)
            {
                if (!TryNumber(tokens[i], out double value))
                    break;
                flags.Add(Math.Abs(value) > 0.5);
            }

            if (flags.Count != 3 && flags.Count != 6)
            {
                Warn($"fix {tag} has {flags.Count} constraint flags; only 3 (ndf 3) and 6 (ndf 6) are supported.");
                return;
            }

            var support = new Support(position,
                flags[0], flags[1], flags[2],
                flags.Count == 6 && flags[3],
                flags.Count == 6 && flags[4],
                flags.Count == 6 && flags[5])
            {
                // Assemble sets this again from the node clouds; it is set here so a support written
                // before assembly still serialises with the right arity.
                ndf = flags.Count,
            };

            _supports.Add(support);
        }

        private void ReadElement(string[] tokens)
        {
            var type = tokens[1];

            if (string.Equals(type, "forceBeamColumn", StringComparison.OrdinalIgnoreCase))
                ReadBeam(tokens);
            else if (string.Equals(type, "ASDShellQ4", StringComparison.OrdinalIgnoreCase))
                ReadShell(tokens, 4, type);
            else if (string.Equals(type, "ASDShellT3", StringComparison.OrdinalIgnoreCase) ||
                     string.Equals(type, "ShellDKGT", StringComparison.OrdinalIgnoreCase) ||
                     string.Equals(type, "ShellNLDKGT", StringComparison.OrdinalIgnoreCase))
                ReadShell(tokens, 3, type);
            else if (string.Equals(type, "SSPbrick", StringComparison.OrdinalIgnoreCase))
                ReadBrick(tokens, 8, type);
            else if (string.Equals(type, "FourNodeTetrahedron", StringComparison.OrdinalIgnoreCase))
                ReadBrick(tokens, 4, type);
            else
                Warn($"element {type} is not supported and was skipped.");
        }

        private void ReadBeam(string[] tokens)
        {
            // element forceBeamColumn $tag $iNode $jNode $transfTag <integration spec> -mass $m
            int tag = Tag(tokens, 2);
            var start = NodeAt(tokens, 3);
            var end = NodeAt(tokens, 4);
            int transfTag = Tag(tokens, 5);

            var curve = new LineCurve(start, end);

            if (!_transforms.TryGetValue(transfTag, out var transf))
            {
                Warn($"element {tag} refers to geomTransf {transfTag}, which is not in the file; a Linear transform about global Z was used.");
                transf = (GeomTransfType.Linear, Vector3d.ZAxis);
            }
            var geomTransf = new GeomTransf(transf.Type, curve, transf.LocalZ);

            IBeam beam;
            var integration = tokens.Length > 6 ? tokens[6] : string.Empty;

            if (string.Equals(integration, "HingeRadau", StringComparison.OrdinalIgnoreCase))
            {
                // HingeRadau $secTagI $lpI $secTagJ $lpJ $secTagE - the two hinge sections are the
                // interior section with the released properties scaled down, which is how the releases
                // are read back out.
                var interior = SectionAt(tokens, 11, tag);
                var hingeI = SectionAt(tokens, 7, tag);
                var hingeJ = SectionAt(tokens, 9, tag);

                // The deck carries lp as a length; BeamWithHinges is set with lp/L.
                var ratioI = LpRatioIn(curve, Number(tokens, 8), tag, "lpI");
                var ratioJ = LpRatioIn(curve, Number(tokens, 10), tag, "lpJ");

                beam = new BeamWithHinges(curve, interior, geomTransf,
                    ReleaseOf(hingeI, interior), ratioI,
                    ReleaseOf(hingeJ, interior), ratioJ);
            }
            else
            {
                if (!string.Equals(integration, "NewtonCotes", StringComparison.OrdinalIgnoreCase))
                    Warn($"element {tag} uses the {integration} integration; Alpaca4d rebuilt it with NewtonCotes.");

                var section = SectionAt(tokens, 7, tag);
                var beamColumn = new ForceBeamColumn(curve, section, geomTransf);

                if (tokens.Length > 8 && TryTag(tokens[8], out int points) && points > 0)
                    beamColumn.BeamIntegration = new NewtonContes(section, points);

                beam = beamColumn;
            }

            // Density never reaches the deck on its own: the element's -mass is the section's mass per
            // unit length in tonnes, which together with the area gives back rho.
            var mass = OptionalFlagValue(tokens, "-mass");
            if (mass.HasValue && beam.Section.Area > 0.0)
                beam.Section.Material.Rho = Alpaca4d.ModelMass.ToKg(mass.Value) / beam.Section.Area;
            else if (!mass.HasValue)
                Warn($"element {tag} carries no -mass, so its density is unknown and its self weight will read as zero.");

            _elements.Add(beam);
            _beamsByTag[tag] = beam;
        }

        /// <summary>
        /// Turns a hinge length from the deck into the lp/L that BeamWithHinges is set with.
        /// A deck written elsewhere may sit outside the range HingeRadau can integrate, and the
        /// constructor clamps it, so say so rather than let the element change quietly on import.
        /// </summary>
        private double? LpRatioIn(Curve curve, double lp, int tag, string which)
        {
            double length = BeamWithHinges.ChordLength(curve);
            if (length <= 0.0 || lp <= 0.0) return null;

            double ratio = lp / length;
            double resolved = BeamWithHinges.ResolveLpRatio(ratio);

            if (Math.Abs(resolved - ratio) > 1e-12)
                Warn($"element {tag} has {which}/L = {ratio:G4}, outside " +
                     $"[{BeamWithHinges.MinLpRatio}, {BeamWithHinges.MaxLpRatio}]; it was clamped to {resolved:G4}.");

            return ratio;
        }

        /// <summary>
        /// Recovers the end releases of a BeamWithHinges. BeamWithHinges.CreateHingeSection multiplies
        /// each released property by 1e-6, so a hinge property that is still close to the interior one
        /// means that degree of freedom was held.
        /// </summary>
        private static Release ReleaseOf(IUniaxialSection hinge, IUniaxialSection interior)
        {
            bool Held(double hingeValue, double interiorValue)
            {
                // A property that is zero to begin with carries no information; call it held.
                if (Math.Abs(interiorValue) <= double.Epsilon)
                    return true;
                return Math.Abs(hingeValue / interiorValue) > 1e-3;
            }

            return new Release(
                Held(hinge.Area, interior.Area),
                Held(hinge.AlphaY, interior.AlphaY),
                Held(hinge.AlphaZ, interior.AlphaZ),
                Held(hinge.J, interior.J),
                Held(hinge.Iyy, interior.Iyy),
                Held(hinge.Izz, interior.Izz));
        }

        private void ReadShell(string[] tokens, int vertexCount, string type)
        {
            int tag = Tag(tokens, 2);
            var mesh = ShellMeshOf(tokens, 3, vertexCount);
            var section = PlateSectionAt(tokens, 3 + vertexCount, tag);

            int after = 4 + vertexCount;
            bool corotational = HasFlag(tokens, "-corotational");
            var localX = Vector3d.Zero;
            int localAt = Array.FindIndex(tokens, t => string.Equals(t, "-local", StringComparison.OrdinalIgnoreCase));
            if (localAt >= after && localAt + 3 < tokens.Length)
                localX = new Vector3d(Number(tokens, localAt + 1), Number(tokens, localAt + 2), Number(tokens, localAt + 3));

            if (string.Equals(type, "ASDShellQ4", StringComparison.OrdinalIgnoreCase))
                _elements.Add(new ASDShellQ4(mesh, section, localX, corotational));
            else if (string.Equals(type, "ASDShellT3", StringComparison.OrdinalIgnoreCase))
                _elements.Add(new ASDShellT3(mesh, section, localX, corotational));
            else
                _elements.Add(new ShellDKGT(mesh, section,
                    isNonLinear: string.Equals(type, "ShellNLDKGT", StringComparison.OrdinalIgnoreCase)));
        }

        private void ReadBrick(string[] tokens, int vertexCount, string type)
        {
            int tag = Tag(tokens, 2);
            var mesh = SolidMeshOf(tokens, 3, vertexCount);

            int materialTag = Tag(tokens, 3 + vertexCount);
            if (!_ndMaterials.TryGetValue(materialTag, out var material))
                throw new InvalidOperationException($"element {tag} refers to nDMaterial {materialTag}, which is not in the file.");

            double? bodyForce = tokens.Length > 4 + vertexCount && TryNumber(tokens[4 + vertexCount], out double b) ? b : (double?)null;

            if (string.Equals(type, "SSPbrick", StringComparison.OrdinalIgnoreCase))
                _elements.Add(new SSPbrick(mesh, material) { BodyForce = bodyForce });
            else
                _elements.Add(new Tetrahedron(mesh, material) { BodyForce = bodyForce });
        }

        private void ReadMass(string[] tokens)
        {
            int tag = Tag(tokens, 1);
            if (!_nodes.TryGetValue(tag, out var position))
            {
                Warn($"mass refers to node {tag}, which is not in the file.");
                return;
            }

            var values = ReadTrailingNumbers(tokens, 2);
            if (values.Count < 3)
            {
                Warn($"mass {tag} has fewer than three components and was skipped.");
                return;
            }

            _masses.Add(new MassLoad(position,
                MassLoad.FromModelUnits(Vector(values, 0)),
                values.Count >= 6 ? MassLoad.FromModelUnits(Vector(values, 3)) : Vector3d.Zero));
        }

        private void ReadEqualDof(string[] tokens)
        {
            int masterTag = Tag(tokens, 1);
            int slaveTag = Tag(tokens, 2);

            if (!_nodes.TryGetValue(masterTag, out var master) || !_nodes.TryGetValue(slaveTag, out var slave))
            {
                Warn($"equalDOF {masterTag} {slaveTag} refers to a node that is not in the file.");
                return;
            }

            // Assemble writes its own equalDOF wherever a 3-dof node meets a 6-dof one, and always puts
            // the 3-dof node first. Re-importing those would double them up on the next assembly.
            if (_nodeNdf.TryGetValue(masterTag, out int masterNdf) && masterNdf == 3)
                return;

            var dofs = new bool[6];
            for (int i = 3; i < tokens.Length; i++)
            {
                if (TryTag(tokens[i], out int dof) && dof >= 1 && dof <= 6)
                    dofs[dof - 1] = true;
            }

            _constraints.Add(new EqualDOF(master, slave, dofs[0], dofs[1], dofs[2], dofs[3], dofs[4], dofs[5]));
        }

        private void ReadRigidDiaphragm(string[] tokens)
        {
            int direction = Tag(tokens, 1);
            int masterTag = Tag(tokens, 2);

            if (!_nodes.TryGetValue(masterTag, out var master))
            {
                Warn($"rigidDiaphragm refers to node {masterTag}, which is not in the file.");
                return;
            }

            var slaves = new List<Point3d>();
            for (int i = 3; i < tokens.Length; i++)
            {
                if (TryTag(tokens[i], out int slaveTag) && _nodes.TryGetValue(slaveTag, out var slave))
                    slaves.Add(slave);
            }

            if (slaves.Count == 0)
            {
                Warn($"rigidDiaphragm about node {masterTag} has no constrained node Alpaca4d could find.");
                return;
            }

            _constraints.Add(new RigidDiaphragm(slaves, master, direction));
        }

        private void ReadRigidLink(string[] tokens)
        {
            if (!Enum.TryParse(tokens[1], true, out RigidLinkType type))
            {
                Warn($"rigidLink {tokens[1]} is not a known type; beam was used instead.");
                type = RigidLinkType.beam;
            }

            int retainedTag = Tag(tokens, 2);
            int constrainedTag = Tag(tokens, 3);

            if (!_nodes.TryGetValue(retainedTag, out var retained) || !_nodes.TryGetValue(constrainedTag, out var constrained))
            {
                Warn($"rigidLink {retainedTag} {constrainedTag} refers to a node that is not in the file.");
                return;
            }

            _constraints.Add(new RigidLink(retained, constrained, type));
        }

        private (LoadPattern, List<ILoad>) ReadPattern(string[] tokens)
        {
            var type = tokens[1];
            int tag = Tag(tokens, 2);
            double factor = OptionalFlagValue(tokens, "-fact") ?? 1.0;

            if (string.Equals(type, "UniformExcitation", StringComparison.OrdinalIgnoreCase))
            {
                // pattern UniformExcitation $tag $dir -accel $tsTag -vel0 $v0 -fact $f
                int direction = Tag(tokens, 3);
                int seriesTag = (int)(OptionalFlagValue(tokens, "-accel") ?? 0.0);

                if (!_timeSeries.TryGetValue(seriesTag, out var accel))
                {
                    Warn($"pattern UniformExcitation {tag} refers to timeSeries {seriesTag}, which is not in the file, and was skipped.");
                    return (null, null);
                }

                _patterns.Add(LoadPattern.CreateUniformExcitation((Direction)direction, accel,
                    OptionalFlagValue(tokens, "-vel0") ?? 0.0, factor));

                // Not a braced pattern: nothing follows for this one.
                return (null, null);
            }

            if (!string.Equals(type, "Plain", StringComparison.OrdinalIgnoreCase))
            {
                Warn($"pattern {type} is not supported and was skipped.");
                return (null, null);
            }

            int plainSeriesTag = Tag(tokens, 3);
            if (!_timeSeries.TryGetValue(plainSeriesTag, out var series))
            {
                Warn($"pattern Plain {tag} refers to timeSeries {plainSeriesTag}, which is not in the file; a constant series was used.");
                series = new Constant(1.0);
            }

            // The loads are collected until the matching "}", then handed to the pattern: LoadPattern's
            // constructor stamps its own id onto the series, so it can only be built once.
            var pattern = new LoadPattern { PatternType = PatternType.Plain, TimeSeries = series, Factor = factor };
            pattern.TimeSeries.Id = (int)pattern.Id;

            return (pattern, new List<ILoad>());
        }

        private ILoad ReadNodalLoad(string[] tokens, ITimeSeries series)
        {
            int tag = Tag(tokens, 1);
            if (!_nodes.TryGetValue(tag, out var position))
                throw new InvalidOperationException($"load refers to node {tag}, which is not in the file.");

            var values = ReadTrailingNumbers(tokens, 2);
            if (values.Count < 3)
                throw new FormatException($"load {tag} has fewer than three components.");

            return new PointLoad(position, Vector(values, 0), values.Count >= 6 ? Vector(values, 3) : Vector3d.Zero, series);
        }

        private ILoad ReadElementLoad(string[] tokens, ITimeSeries series)
        {
            // eleLoad -ele $tag -type -beamUniform $Wy $Wz <$Wx>
            int eleAt = Array.FindIndex(tokens, t => string.Equals(t, "-ele", StringComparison.OrdinalIgnoreCase));
            int uniformAt = Array.FindIndex(tokens, t => string.Equals(t, "-beamUniform", StringComparison.OrdinalIgnoreCase));

            if (eleAt < 0 || uniformAt < 0)
                throw new NotSupportedException("only \"eleLoad -ele <tag> -type -beamUniform\" is supported.");

            int tag = Tag(tokens, eleAt + 1);
            if (!_beamsByTag.TryGetValue(tag, out var beam))
                throw new InvalidOperationException($"eleLoad refers to element {tag}, which is not a beam Alpaca4d read.");

            var components = ReadTrailingNumbers(tokens, uniformAt + 1);
            if (components.Count < 2)
                throw new FormatException("-beamUniform needs at least Wy and Wz.");

            double wy = components[0];
            double wz = components[1];
            double wx = components.Count > 2 ? components[2] : 0.0;

            // LineLoad stores a global vector and converts it to local itself, so the local components
            // of the deck have to be taken back to global first. Utils.PlaceCoordinates, which does the
            // forward conversion, returns (-w, t, s) in the frame (localZ, localY, localZ x localY).
            var plane = new Plane(Point3d.Origin, beam.GeomTransf.LocalZ, beam.GeomTransf.LocalY);
            var global = wz * plane.XAxis + wy * plane.YAxis - wx * plane.ZAxis;

            return new LineLoad(beam, global, series);
        }

        #endregion

        #region helpers

        private Point3d NodeAt(string[] tokens, int index)
        {
            int tag = Tag(tokens, index);
            if (!_nodes.TryGetValue(tag, out var position))
                throw new InvalidOperationException($"node {tag} is not in the file.");
            return position;
        }

        private Mesh VerticesOf(string[] tokens, int firstIndex, int vertexCount)
        {
            var mesh = new Mesh();
            for (int i = 0; i < vertexCount; i++)
                mesh.Vertices.Add(NodeAt(tokens, firstIndex + i));
            return mesh;
        }

        /// <summary>A single shell face, three or four corners, in the order the element lists them.</summary>
        private Mesh ShellMeshOf(string[] tokens, int firstIndex, int vertexCount)
        {
            var mesh = VerticesOf(tokens, firstIndex, vertexCount);

            if (vertexCount == 3)
                mesh.Faces.AddFace(0, 1, 2);
            else
                mesh.Faces.AddFace(0, 1, 2, 3);

            return mesh;
        }

        /// <summary>
        /// A closed tetrahedron or hexahedron. The faces are wound exactly as Utils.CleanTetrahedron
        /// and Utils.CleanHexahedron wind them, because the element already stores its nodes in the
        /// order those produced - and because a solid whose normals point inwards reports a negative
        /// volume, which would turn up as a negative mass.
        /// </summary>
        private Mesh SolidMeshOf(string[] tokens, int firstIndex, int vertexCount)
        {
            var mesh = VerticesOf(tokens, firstIndex, vertexCount);

            if (vertexCount == 4)
            {
                mesh.Faces.AddFace(0, 2, 1);
                mesh.Faces.AddFace(0, 2, 3);
                mesh.Faces.AddFace(0, 3, 1);
                mesh.Faces.AddFace(1, 3, 2);
            }
            else
            {
                mesh.Faces.AddFace(0, 1, 2, 3);
                mesh.Faces.AddFace(4, 5, 6, 7);
                mesh.Faces.AddFace(1, 2, 6, 5);
                mesh.Faces.AddFace(0, 3, 7, 4);
                mesh.Faces.AddFace(0, 1, 5, 4);
                mesh.Faces.AddFace(3, 2, 6, 7);
            }

            mesh.FaceNormals.ComputeFaceNormals();
            mesh.UnifyNormals();

            return mesh;
        }

        private IUniaxialSection SectionAt(string[] tokens, int index, int elementTag)
        {
            int tag = Tag(tokens, index);
            if (!_uniaxialSections.TryGetValue(tag, out var section))
                throw new InvalidOperationException($"element {elementTag} refers to section {tag}, which is not an \"section Elastic\" in the file.");
            return section;
        }

        private IMultiDimensionSection PlateSectionAt(string[] tokens, int index, int elementTag)
        {
            int tag = Tag(tokens, index);
            if (!_plateSections.TryGetValue(tag, out var section))
                throw new InvalidOperationException($"element {elementTag} refers to section {tag}, which is not a \"section PlateFiber\" in the file.");
            return section;
        }

        /// <summary>Reads consecutive numbers from <paramref name="firstIndex"/> until a non-number appears.</summary>
        private static List<double> ReadTrailingNumbers(string[] tokens, int firstIndex)
        {
            var values = new List<double>();
            for (int i = firstIndex; i < tokens.Length; i++)
            {
                if (!TryNumber(tokens[i], out double value))
                    break;
                values.Add(value);
            }
            return values;
        }

        private static Vector3d Vector(List<double> values, int firstIndex)
        {
            return new Vector3d(values[firstIndex], values[firstIndex + 1], values[firstIndex + 2]);
        }

        private void Warn(string message)
        {
            if (!_warnings.Contains(message))
                _warnings.Add(message);
        }

        #endregion
    }
}
