//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Alpaca4d.Gh.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Alpaca4d.Gh.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Analysis_settings__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Analysis_settings__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ASD_ShellQ4__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("ASD_ShellQ4__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Assemble_Model__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Assemble_Model__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Beam_Forces__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Beam_Forces__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap BeamForcesDiagram__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("BeamForcesDiagram__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap become_a_sponsor {
            get {
                object obj = ResourceManager.GetObject("become a sponsor", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Benchmark__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Benchmark (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Bending_Prestress__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Bending_Prestress__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap brick_Disp__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("brick_Disp__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Brick_Stresses__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Brick_Stresses__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Buy_Me_a_Coffee {
            get {
                object obj = ResourceManager.GetObject("Buy_Me_a_Coffee", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Capture_Viewport__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Capture_Viewport__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Central_Difference__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Central_Difference__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Circular_cross_section {
            get {
                object obj = ResourceManager.GetObject("Circular_cross_section", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Colors__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Colors__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap concreate01 {
            get {
                object obj = ResourceManager.GetObject("concreate01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap concreate02 {
            get {
                object obj = ResourceManager.GetObject("concreate02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Constant_Time_Series__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Constant_Time_Series__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Counter__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Counter__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Custom_code__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Custom code (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Deconstruct__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Deconstruct (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap defModel {
            get {
                object obj = ResourceManager.GetObject("defModel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Deformed_Model__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Deformed_Model__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Deserialize__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Deserialize (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Disassemble_Beam {
            get {
                object obj = ResourceManager.GetObject("Disassemble_Beam", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Disassemble_Beam_Element__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Disassemble_Beam_Element__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Disassemble_Brick_Element__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Disassemble_Brick_Element__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Disassemble_CrossSection__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Disassemble_CrossSection__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disassemble_load {
            get {
                object obj = ResourceManager.GetObject("disassemble_load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Disassemble_Load__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Disassemble_Load__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap disassemble_material {
            get {
                object obj = ResourceManager.GetObject("disassemble_material", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Disassemble_Material__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Disassemble_Material__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Disassemble_Model__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Disassemble_Model__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Disassemble_Shell_Element__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Disassemble_Shell_Element__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap dissassemble {
            get {
                object obj = ResourceManager.GetObject("dissassemble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Donate_Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Donate_Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Elastic_Isotropic_Material__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Elastic_Isotropic_Material__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Elastic_Orthotropic_Material__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Elastic_Orthotropic_Material__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Equal_DOF__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Equal_DOF__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap External_Link__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("External Link (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fiber_Aggregated_Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Fiber Aggregated(Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fiber_Point__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Fiber Point (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fiber_section__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Fiber_section__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Fiber_Stress_Strain__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Fiber Stress Strain (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Force_Beam_Column__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Force_Beam_Column__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Force_Beam_Column_Attributes__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Force_Beam_Column_Attributes__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Four_Node_Tetrahedron__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Four_Node_Tetrahedron__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Generic_Section__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Generic_Section__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Gravity_Load__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Gravity_Load__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap I_Section__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("I_Section__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Karamba_to_Alpaca__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Karamba_to_Alpaca__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Layer__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Layer (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Layered_Shell__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Layered_Shell__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Legend__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Legend__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copyright @ 1999,2000 The Regents of the University of California. All Rights Reserved.
        ///
        ///The Regents grants permission, without fee and without a written license agreement, for (a) use, reproduction, modification, and distribution of this software and its documentation by educational, research, and non-profit entities for noncommercial purposes only; and (b) use, reproduction and modification of this software by other entities for internal purposes only. The above copyright notice, this paragraph and the  [rest of string was truncated]&quot;;.
        /// </summary>
        public static string License {
            get {
                return ResourceManager.GetString("License", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Line_load {
            get {
                object obj = ResourceManager.GetObject("Line_load", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Linear_Time_Series__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Linear_Time_Series__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Load_Control_Integrator__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Load_Control_Integrator__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Load_pattern__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Load_pattern__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Logo {
            get {
                object obj = ResourceManager.GetObject("Logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mass_Point__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Mass_Point__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mesh_Loft__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Mesh_Loft__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Mesh_Series_to_Brick__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Mesh_Series_to_Brick__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap meshForces {
            get {
                object obj = ResourceManager.GetObject("meshForces", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MeshLoad__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("MeshLoad (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MinMax {
            get {
                object obj = ResourceManager.GetObject("MinMax", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap MinMax2 {
            get {
                object obj = ResourceManager.GetObject("MinMax2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Modal_Analysis_Report__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Modal_Analysis_Report__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap modalView {
            get {
                object obj = ResourceManager.GetObject("modalView", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap model_View__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("model_View__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Moment_Curvature_Model__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Moment Curvature Model (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Newmark_Integrator__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Newmark_Integrator__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Nodal_Displacements__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Nodal_Displacements__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Patch__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Patch (Alpaca4d)", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Path_Time_Series__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Path_Time_Series__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Patreon_Supporter__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Patreon_Supporter__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Periodic_Time_Series__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Periodic_Time_Series__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Plate_Fiber__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Plate_Fiber__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Point_Load__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Point_Load__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rayleigh_Damping__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Rayleigh_Damping__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Reaction_Forces__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Reaction_Forces__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Read_Time_History__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Read_Time_History__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rectangular_Hollow_cross_section__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Rectangular_Hollow_cross_section__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rectangular_Section__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Rectangular_Section__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap reinforcing_steel_material {
            get {
                object obj = ResourceManager.GetObject("reinforcing_steel_material", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Response_Spectrum__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Response_Spectrum__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Rigid_Diaphgram__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Rigid_Diaphgram__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Run_Analysis__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Run_Analysis__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Run_Natural_Vibration_Analysis__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Run_Natural_Vibration_Analysis__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Serialize {
            get {
                object obj = ResourceManager.GetObject("Serialize", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Shell_MITC4__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Shell_MITC4__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shellDisp {
            get {
                object obj = ResourceManager.GetObject("shellDisp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap shellStress {
            get {
                object obj = ResourceManager.GetObject("shellStress", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SSP_brick__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("SSP_brick__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Steel_Properties__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Steel_Properties__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap stressShell {
            get {
                object obj = ResourceManager.GetObject("stressShell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Support__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Support__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Tab {
            get {
                object obj = ResourceManager.GetObject("Tab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Text_to_model__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Text_to_model__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Timber_beam_utilisation__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Timber_beam_utilisation__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Timber_Properties__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("Timber_Properties__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap uniaxial_Elastic_Material__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("uniaxial_Elastic_Material__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Uniaxial_Material_steal01 {
            get {
                object obj = ResourceManager.GetObject("Uniaxial_Material_steal01", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Uniaxial_Material_steal02 {
            get {
                object obj = ResourceManager.GetObject("Uniaxial_Material_steal02", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Uniform_excitation {
            get {
                object obj = ResourceManager.GetObject("Uniform_excitation", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap View_Brick_Stresses__Alpaca4d_ {
            get {
                object obj = ResourceManager.GetObject("View_Brick_Stresses__Alpaca4d_", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
