using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Reflection;
using System.Text;
using Grasshopper.Kernel;

namespace Alpaca4d.Testing
{
    /// <summary>
    /// Renders the public surface of every component in the plug-in as stable text.
    ///
    /// The point is the diff. A component's GUID, its parameter count, order, access and
    /// optionality are load-bearing: change one and every Grasshopper file that already
    /// contains the component silently loses wires or data. Snapshotting the whole set
    /// turns that class of accident into a failing test.
    /// </summary>
    public static class ComponentApi
    {
        /// <summary>The compiled Alpaca4d Grasshopper plug-in under test.</summary>
        public static Assembly PluginAssembly
        {
            get { return typeof(Alpaca4d.Gh.RectangleCS).Assembly; }
        }

        /// <summary>Every concrete component type the plug-in publishes, in a stable order.</summary>
        public static IReadOnlyList<Type> ComponentTypes()
        {
            return PluginAssembly
                .GetTypes()
                .Where(t => typeof(GH_Component).IsAssignableFrom(t) && !t.IsAbstract)
                .OrderBy(t => t.FullName, StringComparer.Ordinal)
                .ToList();
        }

        public static string Snapshot()
        {
            var text = new StringBuilder();
            text.AppendLine("# Alpaca4d Grasshopper component API");
            text.AppendLine("# Generated by Alpaca4d.Test - review every diff before approving it.");
            text.AppendLine("# A changed GUID, or a changed parameter order/access, breaks existing .gh files.");
            text.AppendLine();

            foreach (var type in ComponentTypes())
            {
                var component = (GH_Component)Activator.CreateInstance(type);
                Describe(text, type, component);
                text.AppendLine();
            }

            return text.ToString();
        }

        private static void Describe(StringBuilder text, Type type, GH_Component component)
        {
            text.AppendLine(type.FullName);
            text.AppendLine("  guid        " + component.ComponentGuid.ToString("D"));
            text.AppendLine("  name        " + component.Name);
            text.AppendLine("  nickname    " + component.NickName);
            text.AppendLine("  category    " + component.Category + " / " + component.SubCategory);
            text.AppendLine("  exposure    " + component.Exposure);
            text.AppendLine("  obsolete    " + component.Obsolete.ToString(CultureInfo.InvariantCulture));

            var switcher = component as Alpaca4d.UIWidgets.GH_SwitcherComponent;
            if (switcher != null)
            {
                // The declared default is worth recording: a switcher whose default names
                // no registered unit still works (the base class falls back to the first
                // one), so the mismatch is otherwise invisible.
                text.AppendLine("  default     " + (DeclaredDefaultUnit(type, switcher) ?? "<none>"));
                text.AppendLine("  active      " + (switcher.ActiveUnit == null ? "<none>" : switcher.ActiveUnit.Name));

                foreach (var unit in switcher.EvalUnits)
                {
                    text.AppendLine("  unit        " + unit.Name);
                    DescribeParameters(text, "    in ", unit.Inputs.Select(i => i.Parameter));
                    DescribeParameters(text, "    out", unit.Outputs.Select(o => o.Parameter));
                }
                return;
            }

            DescribeParameters(text, "  in ", component.Params.Input);
            DescribeParameters(text, "  out", component.Params.Output);
        }

        private static string DeclaredDefaultUnit(Type type, Alpaca4d.UIWidgets.GH_SwitcherComponent switcher)
        {
            var property = type.GetProperty("DefaultEvaluationUnit",
                BindingFlags.NonPublic | BindingFlags.Instance | BindingFlags.FlattenHierarchy);

            return property == null ? null : (string)property.GetValue(switcher, null);
        }

        private static void DescribeParameters(StringBuilder text, string prefix, IEnumerable<IGH_Param> parameters)
        {
            var index = 0;
            foreach (var param in parameters)
            {
                text.AppendLine(string.Format(CultureInfo.InvariantCulture,
                    "{0} {1,2}  {2} ({3}) : {4} {5}{6}",
                    prefix,
                    index++,
                    param.Name,
                    param.NickName,
                    param.GetType().Name,
                    param.Access,
                    param.Optional ? " optional" : string.Empty));
            }
        }
    }
}
